<a href="https://colab.research.google.com/github/parvezsain786/google-colab/blob/master/1_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **numpy programs**

In [6]:
#create numpy array using list
import numpy as np
my_list = [1,2,3,4]
type(np.array(my_list))
arr = np.array(my_list)
print(arr)
#print(type)

[1 2 3 4]


In [7]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0,11,2)      #start point,end point,sampling


array([ 0,  2,  4,  6,  8, 10])

In [9]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [11]:
np.random.randint(0,10)

5

In [12]:
np.random.randint(0,9,(3,3))

array([[8, 5, 8],
       [0, 2, 6],
       [3, 2, 6]])

In [13]:
np.random.seed(20)            #it is used to print constant value
np.random.randint(0,9,(3,3))

array([[3, 4, 6],
       [7, 2, 0],
       [6, 8, 5]])

In [14]:
print(arr)

[1 2 3 4]


In [19]:
print(arr.max())
print(arr.min())
print(arr.mean())
print(arr.argmax())  #print index value of max element
print(arr.reshape(2,2))

4
1
2.5
3
[[1 2]
 [3 4]]


In [22]:
#For slicing
mat = np.arange(0,9).reshape(3,3)
print(mat)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [29]:
print(mat[0,1])
print(mat[2,2])

1
8


In [35]:
print(mat[0:2,0:2])  #for print array from above array
print(mat[0:1,0:1])

[[0 1]
 [3 4]]
[[0]]
